=== mussonindustrial/embr/modules/periscope/common/src/main/resources/schemas/components/embr.periscope.embedding.json-view/props.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "viewJson": {
            "type": "object",
            "description": "Json representation of the view."
        },
        "viewParams": {
            "type": "object",
            "description": "Parameters for this instance.",
            "default": {}
        },
        "viewStyle": {
            "$ref": "urn:ignition-schema:schemas/style-properties.schema.json",
            "default": {
                "classes": ""
            }
        },
        "useDefaultHeight": {
            "type": "boolean",
            "description": "Use default view height."
        },
        "useDefaultMinHeight": {
            "type": "boolean",
            "description": "Use default minimum view height."
        },
        "useDefaultMinWidth": {
            "type": "boolean",
            "description": "Use default minimum view height."
        },
        "useDefaultWidth": {
            "type": "boolean",
            "description": "Use default view width."
        },
        "style": {
            "$ref": "urn:ignition-schema:schemas/style-properties.schema.json",
            "default": {
                "classes": "",
                "overflow": "auto"
            }
        }
    },
    "type": "object",
    "required": ["viewJson"]
}

=== mussonindustrial/embr/modules/periscope/common/src/main/resources/schemas/components/embr.periscope.embedding.json-view/variants/base.props.json
{
  "viewJson": {
    "custom": {},
    "params": {},
    "props": {},
    "root": {
      "children": [
        {
          "meta": {
            "name": "Label"
          },
          "position": {
            "shrink": 0
          },
          "props": {
            "text": "Json View"
          },
          "type": "ia.display.label"
        }
      ],
      "meta": {
        "name": "root"
      },
      "props": {
        "direction": "column"
      },
      "type": "ia.container.flex"
    }
  },
  "viewParams": {},
  "viewStyle": {
    "classes": ""
  },
  "style": {
    "classes": ""
  }
}
