=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/props.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$defs": {
    },
    "properties": {
        "type": {
            "default": "line",
            "description": "Chart type.",
            "type": "string"
        },
        "options": {
            "description": "Chart options.",
            "type": "object"
        },
        "series": {
            "description": "Chart series.",
            "type": "array"
        },
        "style": {
            "$ref": "urn:ignition-schema:schemas/style-properties.schema.json",
            "default": {
                "classes": ""
            }
        }
    },
    "type": "object",
    "required": ["type", "options", "series"]
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/radar.props.json
{
  "type": "radar",
  "series": [
    {
      "name": "Series 1",
      "data": [
        80,
        50,
        30,
        40,
        100,
        20
      ]
    }
  ],
  "options": {
    "chart": {
      "height": 350,
      "type": "radar"
    },
    "title": {
      "text": "Basic Radar Chart"
    },
    "yaxis": {
      "stepSize": 20
    },
    "xaxis": {
      "categories": [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June"
      ]
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/rangearea.props.json
{
  "type": "rangeArea",
  "series": [
    {
      "type": "rangeArea",
      "name": "Team B Range",
      "data": [
        { "x": "Jan", "y": [1100, 1900] },
        { "x": "Feb", "y": [1200, 1800] },
        { "x": "Mar", "y": [900, 2900] },
        { "x": "Apr", "y": [1400, 2700] },
        { "x": "May", "y": [2600, 3900] },
        { "x": "Jun", "y": [500, 1700] },
        { "x": "Jul", "y": [1900, 2300] },
        { "x": "Aug", "y": [1000, 1500] }
      ]
    },
    {
      "type": "rangeArea",
      "name": "Team A Range",
      "data": [
        { "x": "Jan", "y": [3100, 3400] },
        { "x": "Feb", "y": [4200, 5200] },
        { "x": "Mar", "y": [3900, 4900] },
        { "x": "Apr", "y": [3400, 3900] },
        { "x": "May", "y": [5100, 5900] },
        { "x": "Jun", "y": [5400, 6700] },
        { "x": "Jul", "y": [4300, 4600] },
        { "x": "Aug", "y": [2100, 2900] }
      ]
    },
    {
      "type": "line",
      "name": "Team B Median",
      "data": [
        { "x": "Jan", "y": 1500 },
        { "x": "Feb", "y": 1700 },
        { "x": "Mar", "y": 1900 },
        { "x": "Apr", "y": 2200 },
        { "x": "May", "y": 3000 },
        { "x": "Jun", "y": 1000 },
        { "x": "Jul", "y": 2100 },
        { "x": "Aug", "y": 1200 },
        { "x": "Sep", "y": 1800 },
        { "x": "Oct", "y": 2000 }
      ]
    },
    {
      "type": "line",
      "name": "Team A Median",
      "data": [
        { "x": "Jan", "y": 3300 },
        { "x": "Feb", "y": 4900 },
        { "x": "Mar", "y": 4300 },
        { "x": "Apr", "y": 3700 },
        { "x": "May", "y": 5500 },
        { "x": "Jun", "y": 5900 },
        { "x": "Jul", "y": 4500 },
        { "x": "Aug", "y": 2400 },
        { "x": "Sep", "y": 2100 },
        { "x": "Oct", "y": 1500 }
      ]
    }
  ],
  "options": {
    "chart": {
      "height": 350,
      "type": "rangeArea",
      "animations": {
        "speed": 500
      }
    },
    "colors": ["#d4526e", "#33b2df", "#d4526e", "#33b2df"],
    "dataLabels": {
      "enabled": false
    },
    "fill": {
      "opacity": [0.24, 0.24, 1, 1]
    },
    "forecastDataPoints": {
      "count": 2
    },
    "stroke": {
      "curve": "straight",
      "width": [0, 0, 2, 2]
    },
    "legend": {
      "show": true,
      "customLegendItems": ["Team B", "Team A"],
      "inverseOrder": true
    },
    "title": {
      "text": "Range Area with Forecast Line (Combo)"
    },
    "markers": {
      "hover": {
        "sizeOffset": 5
      }
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/funnel.props.json
{
  "type": "bar",
  "series": [
    {
      "name": "Funnel Series",
      "data": [
        { "x": "Sourced", "y": 1380 },
        { "x": "Screened", "y": 1100 },
        { "x": "Assessed", "y": 990 },
        { "x": "HR Interview", "y": 880 },
        { "x": "Technical", "y": 740 },
        { "x": "Verify", "y": 548 },
        { "x": "Offered", "y": 330 },
        { "x": "Hired", "y": 200 }
      ]
    }
  ],
  "options": {
    "chart": {
      "type": "bar",
      "height": 350,
      "dropShadow": {
        "enabled": true
      }
    },
    "plotOptions": {
      "bar": {
        "borderRadius": 0,
        "horizontal": true,
        "barHeight": "80%",
        "isFunnel": true
      }
    },
    "dataLabels": {
      "enabled": true,
      "formatter": "(val, opt) => opt.w.globals.labels[opt.dataPointIndex] + ':  ' + val",
      "dropShadow": {
        "enabled": true
      }
    },
    "title": {
      "align": "left",
      "text": "Funnel Chart"
    },
    "xaxis": {
      "categories": [
        "Sourced",
        "Screened",
        "Assessed",
        "HR Interview",
        "Technical",
        "Verify",
        "Offered",
        "Hired"
      ]
    },
    "legend": {
      "show": false
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/column.props.json
{
  "type": "bar",
  "series": [
    {
      "name": "Net Profit",
      "data": [
        { "x": "Feb", "y": 44 },
        { "x": "Mar", "y": 55 },
        { "x": "Apr", "y": 57 },
        { "x": "May", "y": 56 },
        { "x": "Jun", "y": 61 },
        { "x": "Jul", "y": 58 },
        { "x": "Aug", "y": 63 },
        { "x": "Sep", "y": 60 },
        { "x": "Oct", "y": 66 }
      ]
    },
    {
      "name": "Revenue",
      "data": [
        { "x": "Feb", "y": 76 },
        { "x": "Mar", "y": 85 },
        { "x": "Apr", "y": 101 },
        { "x": "May", "y": 98 },
        { "x": "Jun", "y": 87 },
        { "x": "Jul", "y": 105 },
        { "x": "Aug", "y": 91 },
        { "x": "Sep", "y": 114 },
        { "x": "Oct", "y": 94 }
      ]
    },
    {
      "name": "Free Cash Flow",
      "data": [
        { "x": "Feb", "y": 35 },
        { "x": "Mar", "y": 41 },
        { "x": "Apr", "y": 36 },
        { "x": "May", "y": 26 },
        { "x": "Jun", "y": 45 },
        { "x": "Jul", "y": 48 },
        { "x": "Aug", "y": 52 },
        { "x": "Sep", "y": 53 },
        { "x": "Oct", "y": 41 }
      ]
    }
  ],
  "options": {
    "chart": {
      "type": "bar",
      "height": 350
    },
    "plotOptions": {
      "bar": {
        "horizontal": false,
        "columnWidth": "55%",
        "borderRadius": 5,
        "borderRadiusApplication": "end"
      }
    },
    "dataLabels": {
      "enabled": false
    },
    "stroke": {
      "show": true,
      "width": 2,
      "colors": ["transparent"]
    },
    "xaxis": {
      "categories": ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"]
    },
    "yaxis": {
      "title": {
        "text": "$ (thousands)"
      }
    },
    "fill": {
      "opacity": 1
    },
    "tooltip": {
      "y": {
        "formatter": "(val) => '$ ' + val + ' thousands'"
      }
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/radialbar.props.json
{
  "type": "radialBar",
  "series": [
    44,
    55,
    67,
    83
  ],
  "options": {
    "chart": {},
    "title": {
      "align": "left",
      "text": "Radial Bar Chart"
    },
    "plotOptions": {
      "radialBar": {
        "dataLabels": {
          "name": {
            "fontSize": "22px"
          },
          "value": {
            "fontSize": "16px"
          },
          "total": {
            "show": true,
            "label": "Total",
            "formatter": "(w) => 249"
          }
        }
      }
    },
    "labels": [
      "Apples",
      "Oranges",
      "Bananas",
      "Berries"
    ]
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/bubble.props.json
{
  "type": "bubble",
  "series": [
    {
      "name": "Bubble1",
      "data": [
        { "x": 45, "y": 87, "z": 30 },
        { "x": 312, "y": 45, "z": 50 },
        { "x": 900, "y": 60, "z": 20 },
        { "x": 123, "y": 22, "z": 35 },
        { "x": 678, "y": 98, "z": 40 },
        { "x": 840, "y": 75, "z": 15 },
        { "x": 305, "y": 34, "z": 18 },
        { "x": 555, "y": 66, "z": 35 },
        { "x": 999, "y": 48, "z": 28 },
        { "x": 111, "y": 20, "z": 10 },
        { "x": 444, "y": 82, "z": 22 },
        { "x": 770, "y": 90, "z": 19 },
        { "x": 204, "y": 35, "z": 25 },
        { "x": 666, "y": 55, "z": 32 },
        { "x": 890, "y": 63, "z": 27 },
        { "x": 178, "y": 41, "z": 33 },
        { "x": 745, "y": 59, "z": 26 },
        { "x": 634, "y": 71, "z": 30 },
        { "x": 350, "y": 50, "z": 21 },
        { "x": 92, "y": 28, "z": 24 }
      ]
    },
    {
      "name": "Bubble2",
      "data": [
        { "x": 100, "y": 55, "z": 15 },
        { "x": 240, "y": 67, "z": 32 },
        { "x": 410, "y": 48, "z": 29 },
        { "x": 670, "y": 80, "z": 38 },
        { "x": 785, "y": 65, "z": 42 },
        { "x": 123, "y": 37, "z": 25 },
        { "x": 351, "y": 53, "z": 31 },
        { "x": 560, "y": 71, "z": 27 },
        { "x": 945, "y": 62, "z": 34 },
        { "x": 33, "y": 18, "z": 11 },
        { "x": 188, "y": 30, "z": 16 },
        { "x": 308, "y": 49, "z": 20 },
        { "x": 589, "y": 64, "z": 39 },
        { "x": 721, "y": 77, "z": 36 },
        { "x": 860, "y": 59, "z": 23 },
        { "x": 428, "y": 33, "z": 14 },
        { "x": 233, "y": 46, "z": 26 },
        { "x": 609, "y": 69, "z": 28 },
        { "x": 1000, "y": 91, "z": 40 },
        { "x": 70, "y": 25, "z": 19 }
      ]
    },
    {
      "name": "Bubble3",
      "data": [
        { "x": 20, "y": 12, "z": 14 },
        { "x": 110, "y": 25, "z": 16 },
        { "x": 230, "y": 34, "z": 22 },
        { "x": 370, "y": 42, "z": 30 },
        { "x": 480, "y": 55, "z": 24 },
        { "x": 520, "y": 63, "z": 29 },
        { "x": 655, "y": 78, "z": 33 },
        { "x": 710, "y": 90, "z": 20 },
        { "x": 825, "y": 48, "z": 15 },
        { "x": 945, "y": 66, "z": 31 },
        { "x": 105, "y": 22, "z": 17 },
        { "x": 215, "y": 39, "z": 19 },
        { "x": 305, "y": 50, "z": 21 },
        { "x": 400, "y": 60, "z": 28 },
        { "x": 580, "y": 69, "z": 34 },
        { "x": 690, "y": 73, "z": 25 },
        { "x": 800, "y": 58, "z": 27 },
        { "x": 900, "y": 61, "z": 35 },
        { "x": 965, "y": 72, "z": 37 },
        { "x": 150, "y": 29, "z": 12 }
      ]
    },
    {
      "name": "Bubble4",
      "data": [
        { "x": 30, "y": 19, "z": 15 },
        { "x": 125, "y": 35, "z": 22 },
        { "x": 245, "y": 44, "z": 25 },
        { "x": 365, "y": 57, "z": 30 },
        { "x": 485, "y": 62, "z": 32 },
        { "x": 515, "y": 74, "z": 29 },
        { "x": 645, "y": 81, "z": 27 },
        { "x": 755, "y": 66, "z": 33 },
        { "x": 845, "y": 54, "z": 18 },
        { "x": 920, "y": 63, "z": 26 },
        { "x": 115, "y": 26, "z": 14 },
        { "x": 225, "y": 41, "z": 17 },
        { "x": 335, "y": 49, "z": 19 },
        { "x": 450, "y": 58, "z": 21 },
        { "x": 560, "y": 67, "z": 24 },
        { "x": 670, "y": 74, "z": 28 },
        { "x": 785, "y": 80, "z": 35 },
        { "x": 895, "y": 69, "z": 38 },
        { "x": 980, "y": 72, "z": 40 },
        { "x": 50, "y": 30, "z": 20 }
      ]
    }
  ],
  "options": {
    "chart": {
      "height": 350,
      "type": "bubble"
    },
    "dataLabels": {
      "enabled": false
    },
    "fill": {
      "opacity": 0.8
    },
    "title": {
      "align": "left",
      "text": "Bubble Chart"
    },
    "xaxis": {
      "tickAmount": 12,
      "type": "category"
    },
    "yaxis": {
      "max": 100
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/timeline.props.json
{
  "type": "rangeBar",
  "series": [
    {
      "name": "George Washington",
      "data": [
        {
          "x": "President",
          "y": [
            637311360000,
            856639680000
          ]
        }
      ]
    },
    {
      "name": "John Adams",
      "data": [
        {
          "x": "President",
          "y": [
            856639680000,
            889782720000
          ]
        },
        {
          "x": "Vice President",
          "y": [
            637309440000,
            856639680000
          ]
        }
      ]
    },
    {
      "name": "Thomas Jefferson",
      "data": [
        {
          "x": "President",
          "y": [
            889782720000,
            937736640000
          ]
        },
        {
          "x": "Vice President",
          "y": [
            856639680000,
            889782720000
          ]
        },
        {
          "x": "Secretary of State",
          "y": [
            644567040000,
            755891520000
          ]
        }
      ]
    },
    {
      "name": "Aaron Burr",
      "data": [
        {
          "x": "Vice President",
          "y": [
            889782720000,
            910358400000
          ]
        }
      ]
    },
    {
      "name": "George Clinton",
      "data": [
        {
          "x": "Vice President",
          "y": [
            910358400000,
            980167680000
          ]
        }
      ]
    },
    {
      "name": "John Jay",
      "data": [
        {
          "x": "Secretary of State",
          "y": [
            631866240000,
            644567040000
          ]
        }
      ]
    },
    {
      "name": "Edmund Randolph",
      "data": [
        {
          "x": "Secretary of State",
          "y": [
            757052160000,
            777441600000
          ]
        }
      ]
    },
    {
      "name": "Timothy Pickering",
      "data": [
        {
          "x": "Secretary of State",
          "y": [
            777441600000,
            827838720000
          ]
        }
      ]
    },
    {
      "name": "Charles Lee",
      "data": [
        {
          "x": "Secretary of State",
          "y": [
            827838720000,
            828635200000
          ]
        }
      ]
    },
    {
      "name": "John Marshall",
      "data": [
        {
          "x": "Secretary of State",
          "y": [
            828635200000,
            856639680000
          ]
        }
      ]
    },
    {
      "name": "Levi Lincoln",
      "data": [
        {
          "x": "Secretary of State",
          "y": [
            856639680000,
            860177280000
          ]
        }
      ]
    },
    {
      "name": "James Madison",
      "data": [
        {
          "x": "Secretary of State",
          "y": [
            860177280000,
            926297280000
          ]
        }
      ]
    }
  ],
  "options": {
    "chart": {
      "height": 350,
      "type": "rangeBar"
    },
    "title": {
      "align": "left",
      "text": "Timeline Chart"
    },
    "plotOptions": {
      "bar": {
        "horizontal": true,
        "barHeight": "50%",
        "rangeBarGroupRows": true
      }
    },
    "colors": [
      "#008FFB", "#00E396", "#FEB019", "#FF4560", "#775DD0",
      "#3F51B5", "#546E7A", "#D4526E", "#8D5B4C", "#F86624",
      "#D7263D", "#1B998B", "#2E294E", "#F46036", "#E2C044"
    ],
    "fill": {
      "type": "solid"
    },
    "xaxis": {
      "type": "datetime"
    },
    "legend": {
      "position": "right"
    },
    "tooltip": {
      "custom": "(opts) => { const fromYear = new Date(opts.y1).getFullYear(); const toYear = new Date(opts.y2).getFullYear(); const w = opts.ctx.w; let ylabel = ''; if(w.config.series[opts.seriesIndex].data && w.config.series[opts.seriesIndex].data[opts.dataPointIndex]) { ylabel = w.config.series[opts.seriesIndex].data[opts.dataPointIndex].x; } let seriesName = w.config.series[opts.seriesIndex].name ? w.config.series[opts.seriesIndex].name : ''; const color = w.globals.colors[opts.seriesIndex]; return ('<div class=\"apexcharts-tooltip-rangebar\"><div><span class=\"series-name\" style=\"color: ' + color + '\">' + (seriesName ? seriesName : '') + '</span></div><div><span class=\"category\">' + ylabel + ' </span><span class=\"value start-value\">' + fromYear + '</span><span class=\"separator\">-</span><span class=\"value end-value\">' + toYear + '</span></div></div>'); }"
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/line.props.json
{
  "type": "line",
  "series": [
    {
      "name": "Session Duration",
      "data": [
        { "x": "01 Jan", "y": 45 },
        { "x": "02 Jan", "y": 52 },
        { "x": "03 Jan", "y": 38 },
        { "x": "04 Jan", "y": 24 },
        { "x": "05 Jan", "y": 33 },
        { "x": "06 Jan", "y": 26 },
        { "x": "07 Jan", "y": 21 },
        { "x": "08 Jan", "y": 20 },
        { "x": "09 Jan", "y": 6 },
        { "x": "10 Jan", "y": 8 },
        { "x": "11 Jan", "y": 15 },
        { "x": "12 Jan", "y": 10 }
      ]
    },
    {
      "name": "Page Views",
      "data": [
        { "x": "01 Jan", "y": 35 },
        { "x": "02 Jan", "y": 41 },
        { "x": "03 Jan", "y": 62 },
        { "x": "04 Jan", "y": 42 },
        { "x": "05 Jan", "y": 13 },
        { "x": "06 Jan", "y": 18 },
        { "x": "07 Jan", "y": 29 },
        { "x": "08 Jan", "y": 37 },
        { "x": "09 Jan", "y": 36 },
        { "x": "10 Jan", "y": 51 },
        { "x": "11 Jan", "y": 32 },
        { "x": "12 Jan", "y": 35 }
      ]
    },
    {
      "name": "Total Visits",
      "data": [
        { "x": "01 Jan", "y": 87 },
        { "x": "02 Jan", "y": 57 },
        { "x": "03 Jan", "y": 74 },
        { "x": "04 Jan", "y": 99 },
        { "x": "05 Jan", "y": 75 },
        { "x": "06 Jan", "y": 38 },
        { "x": "07 Jan", "y": 62 },
        { "x": "08 Jan", "y": 47 },
        { "x": "09 Jan", "y": 82 },
        { "x": "10 Jan", "y": 56 },
        { "x": "11 Jan", "y": 45 },
        { "x": "12 Jan", "y": 47 }
      ]
    }
  ],
  "options": {
    "chart": {
      "zoom": {
        "enabled": false
      }
    },
    "dataLabels": {
      "enabled": false
    },
    "stroke": {
      "width": [5, 7, 5],
      "curve": "straight",
      "dashArray": [0, 8, 5]
    },
    "title": {
      "align": "left",
      "text": "Line Chart"
    },
    "legend": {
      "tooltipHoverFormatter": "(val, opts) => val + ' - <strong>' + opts.w.globals.series[opts.seriesIndex][opts.dataPointIndex] + '</strong>'"
    },
    "markers": {
      "size": 0,
      "hover": {
        "sizeOffset": 6
      }
    },
    "xaxis": {
      "position": "bottom"
    },
    "tooltip": {
      "y": [
        {
          "title": {
            "formatter": "val => val + ' (mins)'"
          }
        },
        {
          "title": {
            "formatter": "val => val + ' per session'"
          }
        },
        {
          "title": {
            "formatter": "val => val"
          }
        }
      ]
    },
    "grid": {
      "borderColor": "#f1f1f1"
    }
  },
  "style": {}
}
