=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/props.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$defs": {
    },
    "properties": {
        "type": {
            "default": "line",
            "description": "Chart type.",
            "type": "string"
        },
        "options": {
            "description": "Chart options.",
            "type": "object"
        },
        "series": {
            "description": "Chart series.",
            "type": "array"
        },
        "style": {
            "$ref": "urn:ignition-schema:schemas/style-properties.schema.json",
            "default": {
                "classes": ""
            }
        }
    },
    "type": "object",
    "required": ["type", "options", "series"]
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/pie.props.json
{
  "type": "donut",
  "series": [
    44,
    55,
    41,
    17,
    15
  ],
  "options": {
    "chart": {
      "type": "donut"
    },
    "title": {
      "align": "left",
      "text": "Pie Chart"
    },
    "responsive": [
      {
        "breakpoint": 480,
        "options": {
          "chart": {
            "width": 200
          },
          "legend": {
            "position": "bottom"
          }
        }
      }
    ]
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/bar.props.json
{
  "type": "bar",
  "series": [
    {
      "name": "Marine Sprite",
      "data": [
        { "x": "2012", "y": 22 },
        { "x": "2013", "y": 43 },
        { "x": "2014", "y": 21 }
      ]
    },
    {
      "name": "Striking Calf",
      "data": [
        { "x": "2012", "y": 13 },
        { "x": "2013", "y": 43 },
        { "x": "2014", "y": 32 }
      ]
    },
    {
      "name": "Tank Picture",
      "data": [
        { "x": "2012", "y": 15 },
        { "x": "2013", "y": 11 },
        { "x": "2014", "y": 20 }
      ]
    },
    {
      "name": "Bucket Slope",
      "data": [
        { "x": "2012", "y": 6 },
        { "x": "2013", "y": 9 },
        { "x": "2014", "y": 4 }
      ]
    },
    {
      "name": "Reborn Kid",
      "data": [
        { "x": "2012", "y": 25 },
        { "x": "2013", "y": 24 },
        { "x": "2014", "y": 10 }
      ]
    }
  ],
  "options": {
    "chart": {},
    "plotOptions": {
      "bar": {
        "horizontal": true,
        "dataLabels": {
          "total": {
            "enabled": true,
            "offsetX": 0,
            "style": {
              "fontSize": "13px",
              "fontWeight": 900
            }
          }
        }
      }
    },
    "dataLabels": {
      "enabled": false
    },
    "stroke": {
      "width": 1,
      "colors": ["#fff"]
    },
    "title": {
      "align": "left",
      "text": "Bar Chart"
    },
    "xaxis": {
      "position": "bottom",
      "labels": {
        "formatter": "(val) => val + 'K'"
      }
    },
    "tooltip": {
      "y": {
        "formatter": "(val) => val + 'K'"
      }
    },
    "fill": {
      "opacity": 1
    },
    "legend": {
      "position": "top",
      "horizontalAlign": "left",
      "offsetX": 40
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/heatmap.props.json
{
  "type": "heatmap",
  "series": [
    {
      "name": "Metric1",
      "data": [
        { "x": 0, "y": 12 },
        { "x": 1, "y": 16 },
        { "x": 2, "y": 23 },
        { "x": 3, "y": 36 },
        { "x": 4, "y": 15 },
        { "x": 5, "y": 50 },
        { "x": 6, "y": 28 },
        { "x": 7, "y": 42 },
        { "x": 8, "y": 47 },
        { "x": 9, "y": 56 },
        { "x": 10, "y": 63 },
        { "x": 11, "y": 52 },
        { "x": 12, "y": 22 },
        { "x": 13, "y": 37 },
        { "x": 14, "y": 19 },
        { "x": 15, "y": 32 },
        { "x": 16, "y": 25 },
        { "x": 17, "y": 44 }
      ]
    },
    {
      "name": "Metric2",
      "data": [
        { "x": 0, "y": 33 },
        { "x": 1, "y": 45 },
        { "x": 2, "y": 18 },
        { "x": 3, "y": 30 },
        { "x": 4, "y": 41 },
        { "x": 5, "y": 59 },
        { "x": 6, "y": 22 },
        { "x": 7, "y": 13 },
        { "x": 8, "y": 50 },
        { "x": 9, "y": 31 },
        { "x": 10, "y": 27 },
        { "x": 11, "y": 40 },
        { "x": 12, "y": 52 },
        { "x": 13, "y": 29 },
        { "x": 14, "y": 56 },
        { "x": 15, "y": 63 },
        { "x": 16, "y": 19 },
        { "x": 17, "y": 32 }
      ]
    },
    {
      "name": "Metric3",
      "data": [
        { "x": 0, "y": 38 },
        { "x": 1, "y": 50 },
        { "x": 2, "y": 28 },
        { "x": 3, "y": 63 },
        { "x": 4, "y": 22 },
        { "x": 5, "y": 54 },
        { "x": 6, "y": 39 },
        { "x": 7, "y": 51 },
        { "x": 8, "y": 45 },
        { "x": 9, "y": 60 },
        { "x": 10, "y": 30 },
        { "x": 11, "y": 42 },
        { "x": 12, "y": 19 },
        { "x": 13, "y": 57 },
        { "x": 14, "y": 48 },
        { "x": 15, "y": 31 },
        { "x": 16, "y": 55 },
        { "x": 17, "y": 28 }
      ]
    },
    {
      "name": "Metric4",
      "data": [
        { "x": 0, "y": 22 },
        { "x": 1, "y": 27 },
        { "x": 2, "y": 33 },
        { "x": 3, "y": 25 },
        { "x": 4, "y": 40 },
        { "x": 5, "y": 32 },
        { "x": 6, "y": 48 },
        { "x": 7, "y": 45 },
        { "x": 8, "y": 52 },
        { "x": 9, "y": 41 },
        { "x": 10, "y": 37 },
        { "x": 11, "y": 44 },
        { "x": 12, "y": 27 },
        { "x": 13, "y": 34 },
        { "x": 14, "y": 29 },
        { "x": 15, "y": 31 },
        { "x": 16, "y": 46 },
        { "x": 17, "y": 56 }
      ]
    },
    {
      "name": "Metric5",
      "data": [
        { "x": 0, "y": 41 },
        { "x": 1, "y": 39 },
        { "x": 2, "y": 56 },
        { "x": 3, "y": 44 },
        { "x": 4, "y": 59 },
        { "x": 5, "y": 38 },
        { "x": 6, "y": 51 },
        { "x": 7, "y": 43 },
        { "x": 8, "y": 29 },
        { "x": 9, "y": 50 },
        { "x": 10, "y": 64 },
        { "x": 11, "y": 36 },
        { "x": 12, "y": 32 },
        { "x": 13, "y": 40 },
        { "x": 14, "y": 27 },
        { "x": 15, "y": 42 },
        { "x": 16, "y": 28 },
        { "x": 17, "y": 46 }
      ]
    },
    {
      "name": "Metric6",
      "data": [
        { "x": 0, "y": 45 },
        { "x": 1, "y": 47 },
        { "x": 2, "y": 38 },
        { "x": 3, "y": 50 },
        { "x": 4, "y": 62 },
        { "x": 5, "y": 33 },
        { "x": 6, "y": 56 },
        { "x": 7, "y": 34 },
        { "x": 8, "y": 39 },
        { "x": 9, "y": 61 },
        { "x": 10, "y": 42 },
        { "x": 11, "y": 54 },
        { "x": 12, "y": 28 },
        { "x": 13, "y": 46 },
        { "x": 14, "y": 43 },
        { "x": 15, "y": 30 },
        { "x": 16, "y": 41 },
        { "x": 17, "y": 52 }
      ]
    },
    {
      "name": "Metric7",
      "data": [
        { "x": 0, "y": 32 },
        { "x": 1, "y": 36 },
        { "x": 2, "y": 40 },
        { "x": 3, "y": 46 },
        { "x": 4, "y": 29 },
        { "x": 5, "y": 35 },
        { "x": 6, "y": 41 },
        { "x": 7, "y": 54 },
        { "x": 8, "y": 31 },
        { "x": 9, "y": 50 },
        { "x": 10, "y": 38 },
        { "x": 11, "y": 47 },
        { "x": 12, "y": 39 },
        { "x": 13, "y": 42 },
        { "x": 14, "y": 33 },
        { "x": 15, "y": 48 },
        { "x": 16, "y": 46 },
        { "x": 17, "y": 44 }
      ]
    },
    {
      "name": "Metric8",
      "data": [
        { "x": 0, "y": 39 },
        { "x": 1, "y": 45 },
        { "x": 2, "y": 51 },
        { "x": 3, "y": 49 },
        { "x": 4, "y": 37 },
        { "x": 5, "y": 43 },
        { "x": 6, "y": 35 },
        { "x": 7, "y": 56 },
        { "x": 8, "y": 32 },
        { "x": 9, "y": 41 },
        { "x": 10, "y": 48 },
        { "x": 11, "y": 50 },
        { "x": 12, "y": 37 },
        { "x": 13, "y": 45 },
        { "x": 14, "y": 43 },
        { "x": 15, "y": 30 },
        { "x": 16, "y": 51 },
        { "x": 17, "y": 54 }
      ]
    },
    {
      "name": "Metric9",
      "data": [
        { "x": 0, "y": 31 },
        { "x": 1, "y": 44 },
        { "x": 2, "y": 35 },
        { "x": 3, "y": 55 },
        { "x": 4, "y": 48 },
        { "x": 5, "y": 34 },
        { "x": 6, "y": 46 },
        { "x": 7, "y": 52 },
        { "x": 8, "y": 41 },
        { "x": 9, "y": 36 },
        { "x": 10, "y": 59 },
        { "x": 11, "y": 32 },
        { "x": 12, "y": 45 },
        { "x": 13, "y": 50 },
        { "x": 14, "y": 28 },
        { "x": 15, "y": 43 },
        { "x": 16, "y": 41 },
        { "x": 17, "y": 39 }
      ]
    }
  ],
  "options": {
    "chart": {
      "height": 350,
      "type": "heatmap"
    },
    "dataLabels": {
      "enabled": false
    },
    "colors": ["#008FFB"],
    "title": {
      "text": "HeatMap Chart (Single color)"
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/treemap.props.json
{
  "type": "treemap",
  "series": [
    {
      "data": [
        { "x": "INTC", "y": 1.2 },
        { "x": "GS", "y": 0.4 },
        { "x": "CVX", "y": -1.4 },
        { "x": "GE", "y": 2.7 },
        { "x": "CAT", "y": -0.3 },
        { "x": "RTX", "y": 5.1 },
        { "x": "CSCO", "y": -2.3 },
        { "x": "JNJ", "y": 2.1 },
        { "x": "PG", "y": 0.3 },
        { "x": "TRV", "y": 0.12 },
        { "x": "MMM", "y": -2.31 },
        { "x": "NKE", "y": 3.98 },
        { "x": "IYT", "y": 1.67 }
      ]
    }
  ],
  "options": {
    "legend": {
      "show": false
    },
    "chart": {
      "height": 350,
      "type": "treemap"
    },
    "title": {
      "text": "Treemap with Color scale"
    },
    "dataLabels": {
      "enabled": true,
      "style": {
        "fontSize": "12px"
      },
      "formatter": "(text, op) => [text, op.value]",
      "offsetY": -4
    },
    "plotOptions": {
      "treemap": {
        "enableShades": true,
        "shadeIntensity": 0.5,
        "reverseNegativeShade": true,
        "colorScale": {
          "ranges": [
            {
              "from": -6,
              "to": 0,
              "color": "#CD363A"
            },
            {
              "from": 0.001,
              "to": 6,
              "color": "#52B12C"
            }
          ]
        }
      }
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/boxplot.props.json
{
  "type": "boxPlot",
  "series": [
    {
      "name": "box",
      "type": "boxPlot",
      "data": [
        {
          "x": "Alice",
          "y": [54, 66, 69, 75, 88],
          "goals": [
            {
              "value": 32,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            }
          ]
        },
        {
          "x": "Bob",
          "y": [43, 65, 69, 76, 81],
          "goals": [
            {
              "value": 35,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            },
            {
              "value": 95,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            }
          ]
        },
        {
          "x": "Charlie",
          "y": [31, 39, 45, 51, 59],
          "goals": [
            {
              "value": 64,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            },
            {
              "value": 75,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            }
          ]
        },
        {
          "x": "David",
          "y": [39, 46, 55, 65, 71],
          "goals": [
            {
              "value": 27,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            },
            {
              "value": 77,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            }
          ]
        },
        {
          "x": "Ahmed",
          "y": [29, 31, 35, 39, 44],
          "goals": [
            {
              "value": 10,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            },
            {
              "value": 56,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            },
            {
              "value": 62,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            },
            {
              "value": 98,
              "strokeWidth": 0,
              "strokeHeight": 13,
              "strokeLineCap": "round",
              "strokeColor": "#FEB019"
            }
          ]
        }
      ]
    }
  ],
  "options": {
    "chart": {
      "type": "boxPlot",
      "height": 350
    },
    "colors": ["#008FFB", "#FEB019"],
    "title": {
      "align": "left",
      "text": "Boxplot Chart"
    },
    "xaxis": {
      "type": "category"
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/slope.props.json
{
  "type": "line",
  "series": [
    {
      "name": "Blue",
      "data": [
        { "x": "Category 1", "y": 503 },
        { "x": "Category 2", "y": 580 },
        { "x": "Category 3", "y": 135 }
      ]
    },
    {
      "name": "Green",
      "data": [
        { "x": "Category 1", "y": 733 },
        { "x": "Category 2", "y": 385 },
        { "x": "Category 3", "y": 715 }
      ]
    },
    {
      "name": "Orange",
      "data": [
        { "x": "Category 1", "y": 255 },
        { "x": "Category 2", "y": 211 },
        { "x": "Category 3", "y": 441 }
      ]
    },
    {
      "name": "Red",
      "data": [
        { "x": "Category 1", "y": 428 },
        { "x": "Category 2", "y": 749 },
        { "x": "Category 3", "y": 559 }
      ]
    }
  ],
  "options": {
    "chart": {
      "height": 350,
      "width": 600,
      "type": "line"
    },
    "plotOptions": {
      "line": {
        "isSlopeChart": true
      }
    },
    "tooltip": {
      "followCursor": true,
      "intersect": false,
      "shared": true
    },
    "dataLabels": {
      "background": {
        "enabled": true
      },
      "formatter": "(val, opts) => { const seriesName = opts.w.config.series[opts.seriesIndex].name; return val !== null ? seriesName : ''  }"
    },
    "yaxis": {
      "show": true,
      "labels": {
        "show": true
      }
    },
    "xaxis": {
      "position": "bottom"
    },
    "legend": {
      "show": true,
      "position": "top",
      "horizontalAlign": "left"
    },
    "stroke": {
      "width": [2, 3, 4, 2],
      "dashArray": [0, 0, 5, 2],
      "curve": "smooth"
    }
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/polararea.props.json
{
  "type": "polarArea",
  "series": [
    14,
    23,
    21,
    17,
    15,
    10,
    12,
    17,
    21
  ],
  "options": {
    "chart": {
      "type": "polarArea"
    },
    "stroke": {
      "colors": ["#fff"]
    },
    "title": {
      "align": "left",
      "text": "Polar Area Chart"
    },
    "fill": {
      "opacity": 0.8
    },
    "responsive": [
      {
        "breakpoint": 480,
        "options": {
          "chart": {
            "width": 200
          },
          "legend": {
            "position": "bottom"
          }
        }
      }
    ]
  },
  "style": {}
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/area.props.json
{
  "type": "area",
  "series": [
    {
      "name": "series1",
      "data": [
        { "x": "2018-09-19T00:00:00.000Z", "y": 31 },
        { "x": "2018-09-19T01:30:00.000Z", "y": 40 },
        { "x": "2018-09-19T02:30:00.000Z", "y": 28 },
        { "x": "2018-09-19T03:30:00.000Z", "y": 51 },
        { "x": "2018-09-19T04:30:00.000Z", "y": 42 },
        { "x": "2018-09-19T05:30:00.000Z", "y": 109 },
        { "x": "2018-09-19T06:30:00.000Z", "y": 100 }
      ]
    },
    {
      "name": "series2",
      "data": [
        { "x": "2018-09-19T00:00:00.000Z", "y": 11 },
        { "x": "2018-09-19T01:30:00.000Z", "y": 32 },
        { "x": "2018-09-19T02:30:00.000Z", "y": 45 },
        { "x": "2018-09-19T03:30:00.000Z", "y": 32 },
        { "x": "2018-09-19T04:30:00.000Z", "y": 34 },
        { "x": "2018-09-19T05:30:00.000Z", "y": 52 },
        { "x": "2018-09-19T06:30:00.000Z", "y": 41 }
      ]
    }
  ],
  "options": {
    "chart": {
      "height": 350,
      "type": "area"
    },
    "dataLabels": {
      "enabled": false
    },
    "stroke": {
      "curve": "smooth"
    },
    "xaxis": {
      "type": "datetime",
      "position": "bottom"
    },
    "tooltip": {
      "x": {
        "format": "dd/MM/yy HH:mm"
      }
    }
  },
  "style": {}
}
