=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/props.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$defs": {
    },
    "properties": {
        "type": {
            "default": "line",
            "description": "Chart type.",
            "type": "string"
        },
        "options": {
            "description": "Chart options.",
            "type": "object"
        },
        "series": {
            "description": "Chart series.",
            "type": "array"
        },
        "style": {
            "$ref": "urn:ignition-schema:schemas/style-properties.schema.json",
            "default": {
                "classes": ""
            }
        }
    },
    "type": "object",
    "required": ["type", "options", "series"]
}

=== mussonindustrial/embr/modules/charts/common/src/main/resources/schemas/components/embr.chart.apex-charts/variants/candlestick.props.json
{
  "type": "candlestick",
  "series": [
    {
      "data": [
        { "x": "2018-10-07T00:10:00.000Z", "y": [6629.81, 6650.5, 6623.04, 6633.33] },
        { "x": "2018-10-07T00:40:00.000Z", "y": [6632.01, 6643.59, 6620, 6630.11] },
        { "x": "2018-10-07T01:10:00.000Z", "y": [6630.71, 6648.95, 6623.34, 6635.65] },
        { "x": "2018-10-07T01:40:00.000Z", "y": [6635.65, 6651, 6629.67, 6638.24] },
        { "x": "2018-10-07T02:10:00.000Z", "y": [6638.24, 6640, 6620, 6624.47] },
        { "x": "2018-10-07T02:40:00.000Z", "y": [6624.53, 6636.03, 6621.68, 6624.31] },
        { "x": "2018-10-07T03:10:00.000Z", "y": [6624.61, 6632.2, 6617, 6626.02] },
        { "x": "2018-10-07T03:40:00.000Z", "y": [6627, 6627.62, 6584.22, 6603.02] },
        { "x": "2018-10-07T04:10:00.000Z", "y": [6605, 6608.03, 6598.95, 6604.01] },
        { "x": "2018-10-07T04:40:00.000Z", "y": [6604.5, 6614.4, 6602.26, 6608.02] },
        { "x": "2018-10-07T05:10:00.000Z", "y": [6608.02, 6610.68, 6601.99, 6608.91] },
        { "x": "2018-10-07T05:40:00.000Z", "y": [6608.91, 6618.99, 6608.01, 6612] },
        { "x": "2018-10-07T06:10:00.000Z", "y": [6612, 6615.13, 6605.09, 6612] },
        { "x": "2018-10-07T06:40:00.000Z", "y": [6612, 6624.12, 6608.43, 6622.95] },
        { "x": "2018-10-07T07:10:00.000Z", "y": [6623.91, 6623.91, 6615, 6615.67] },
        { "x": "2018-10-07T07:40:00.000Z", "y": [6618.69, 6618.74, 6610, 6610.4] },
        { "x": "2018-10-07T08:10:00.000Z", "y": [6611, 6622.78, 6610.4, 6614.9] },
        { "x": "2018-10-07T08:40:00.000Z", "y": [6614.9, 6626.2, 6613.33, 6623.45] },
        { "x": "2018-10-07T09:10:00.000Z", "y": [6623.48, 6627, 6618.38, 6620.35] },
        { "x": "2018-10-07T09:40:00.000Z", "y": [6619.43, 6620.35, 6610.05, 6615.53] },
        { "x": "2018-10-07T10:10:00.000Z", "y": [6615.53, 6617.93, 6610, 6615.19] },
        { "x": "2018-10-07T10:40:00.000Z", "y": [6615.19, 6621.6, 6608.2, 6620] },
        { "x": "2018-10-07T11:10:00.000Z", "y": [6619.54, 6625.17, 6614.15, 6620] },
        { "x": "2018-10-07T11:40:00.000Z", "y": [6620.33, 6634.15, 6617.24, 6624.61] },
        { "x": "2018-10-07T12:10:00.000Z", "y": [6625.95, 6626, 6611.66, 6617.58] },
        { "x": "2018-10-07T12:40:00.000Z", "y": [6619, 6625.97, 6595.27, 6598.86] },
        { "x": "2018-10-07T13:10:00.000Z", "y": [6598.86, 6598.88, 6570, 6587.16] },
        { "x": "2018-10-07T13:40:00.000Z", "y": [6588.86, 6600, 6580, 6593.4] },
        { "x": "2018-10-07T14:10:00.000Z", "y": [6593.99, 6598.89, 6585, 6587.81] },
        { "x": "2018-10-07T14:40:00.000Z", "y": [6587.81, 6592.73, 6567.14, 6578] },
        { "x": "2018-10-07T15:10:00.000Z", "y": [6578.35, 6581.72, 6567.39, 6579] },
        { "x": "2018-10-07T15:40:00.000Z", "y": [6579.38, 6580.92, 6566.77, 6575.96] },
        { "x": "2018-10-07T16:10:00.000Z", "y": [6575.96, 6589, 6571.77, 6588.92] },
        { "x": "2018-10-07T16:40:00.000Z", "y": [6588.92, 6594, 6577.55, 6589.22] },
        { "x": "2018-10-07T17:10:00.000Z", "y": [6589.3, 6598.89, 6589.1, 6596.08] }
      ]
    }
  ],
  "options": {
    "chart": {
      "type": "candlestick",
      "height": 350
    },
    "title": {
      "align": "left",
      "text": "Candlestick Chart"
    },
    "xaxis": {
      "type": "datetime"
    },
    "yaxis": {
      "tooltip": {
        "enabled": true
      }
    }
  },
  "style": {}
}
